name: itec
description: Aplicacion oficial del Instituto Tecnológico de Comitán

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.3.3+14

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_web_browser: ^0.11.0
  flutter:
     sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.12.0+4
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  firebase_messaging: ^6.0.9
  image_picker: ^0.6.3
  sqflite: ^1.2.0
  multi_media_picker: ^0.2.3
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  carousel_slider: ^1.4.1
  connectivity: ^0.4.6+2
  local_auth: ^0.6.1
  sliding_up_panel: ^0.3.6
  provider: ^4.0.1
  font_awesome_flutter: ^8.5.0
  wc_flutter_share: ^0.1.1





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
       - family: Montserrat
         fonts:
            - asset: assets/Montserrat-Black.ttf
            - asset: assets/Montserrat-BlackItalic.ttf
            - asset: assets/Montserrat-Bold.ttf
            - asset: assets/Montserrat-BoldItalic.ttf
            - asset: assets/Montserrat-ExtraBold.ttf
            - asset: assets/Montserrat-ExtraBoldItalic.ttf
            - asset: assets/Montserrat-ExtraLight.ttf
            - asset: assets/Montserrat-ExtraLightItalic.ttf
            - asset: assets/Montserrat-Italic.ttf
            - asset: assets/Montserrat-Light.ttf
            - asset: assets/Montserrat-LightItalic.ttf
            - asset: assets/Montserrat-Medium.ttf
            - asset: assets/Montserrat-MediumItalic.ttf
            - asset: assets/Montserrat-Regular.ttf
            - asset: assets/Montserrat-SemiBold.ttf
            - asset: assets/Montserrat-SemiBoldItalic.ttf
            - asset: assets/Montserrat-Thin.ttf
            - asset: assets/Montserrat-ThinItalic.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
